# Arnfinn

Mine egne notater, som er lite interessant for andre

## Bash

`sed` vil konvertere fil fra windows til linux. Gjør derfor følgende:

```
for i in *.sas; do sed -e -i 's/foo/bar/g' $i; unix2dos $i; done
```

## Opprette automatisk dokumentasjonekstrasjon fra SAS-filer

I mange av våre prosjekter på [github](https://github.com/SKDE-Analyse) lages det dokuemtasjonssider automatisk når man oppdaterer koden. Dette gjøres av [Travis CI](https://travis-ci.org/SKDE-Analyse).

- Bruk følgende `.travis.yml` fil:

```yml
language: python

python:
  - "3.6"

before_script:
  # copy version 1.0.0 of the script from github
  - wget https://raw.githubusercontent.com/SKDE-Analyse/python-scripts/v1.0.0/skde/extract_sas_documentation.py

script:
    # Will only extract documentation from sas-files on root directory of project
  - python extract_sas_documentation.py

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master

notifications:
  email: false
```

- Aktiver Travis CI [her](https://travis-ci.org/profile/SKDE-Analyse)

- Trykk på *Settings* og legg inn `GITHUB_TOKEN`. Hent `GITHUB_TOKEN` fra `p/github/token.txt`.

- Legg inn følgende `_config.yml` fil i `docs`-mappe (lag denne mappen hvis den ikke eksisterer):

```
theme: jekyll-theme-minimal
```


## Proxy

- curl gjennom proxy (f.eks for å få været i Tromsø:)):

```
curl.exe --proxy http://www-proxy.helsenord.no:8080/ wttr.in/Tromso
```
- Sette opp proxy generelt (kan eventuelt legges inn i `.bash_profile`:

```bash
export http_proxy=http://www-proxy.helsenord.no:8080/
export https_proxy=https://www-proxy.helsenord.no:8080/
```

## Diverse om figurer

### Fjerne hvit bakgrunn på eps/pdf-filer

- Åpne i Inkscape
- Velg objekt (klikk på bildet)
- Filtre - transparency utilities - Light eraser
- Lagre fil

### Fjerne luft rundt figurer

Ble brukt på figurene til eldrehelseatlas-faktaarkene

`pdfcrop original.pdf croppet.pdf`

## Etter en retank av maskin

Installerer alt på `c/Users/ast046/AppData/Local/Programs/`

1. Installér Chrome og prøv å logg på
2. Installér [git](https://git-scm.com/download/win)
3. Installér [Nodepad++](https://notepad-plus-plus.org/download)
4. Installér [r](https://cran.r-project.org/bin/windows/base/)
5. Installér [RStudio](https://www.rstudio.com/products/rstudio/download/)
6. Installér [MiKTeX](https://miktex.org/download) (basic MiKTeX installer)
7. Installèr [Texmaker](http://www.xm1math.net/texmaker/download.html)
8. Installèr [gvim](http://mirror.netinch.com/pub/vim/pc/) (for å kunne få bedre vimdiff)
9. Installèr [python](https://www.python.org/downloads/) 3 (custom installasjon, slik at man kan skru av "for alle")

### Legge til skriver

- *TOS-UNN-C0.511A-03*

### RStudio

- bytte libpath

```r
> .libPaths()
[1] "\\\\hn.helsenord.no/unn-ansatte/a-ans/ast046/R/library"
[2] "C:/Users/ast046/AppData/Local/Programs/R-3.3.1/library"
> .libPaths("C:/Users/ast046/AppData/Local/Programs/R-3.3.1/library")
> .libPaths()
[1] "C:/Users/ast046/AppData/Local/Programs/R-3.3.1/library"
```

- Installere pakker

```r
install.packages("devtools")
install.packages("shiny")
install.packages("rsconnect")
install.packages("knitr")
install.packages("BH")
install.packages(c("DBI","DT","assertthat","caTools","dplyr", "htmlwidgets", "lazyeval","rmarkdown","tibble"))
install.packages("tidyr")
```

## Bytte standard nettleser

- Kan kun endres hvis man har administratorrettigheter på maskinen. Dette må Helse-Nord IKT gi brukeren.

## Oversettelse, Helseatlas




### Diverse bash-kode

`
cat faktaark-eldre-til-oversettelse_-EN.tex |grep '\\section' | cut -d '{' -f 3 | sed 's/..............$//' > ../../list_factsheets_elderly.txt
`



## Kompilere denne dokumentasjonen lokalt


### Linux

*R* må være installert, samt pakken *bookdown*. Gjør følgende i terminal (dette gjelder for Debian/Ubuntu:

```bash
sudo apt-get install r-base-core 
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libssl-dev
sudo Rscript -e 'install.packages("devtools","/usr/local/lib/R/site-library","http://cran.r-project.org")'
sudo apt-get install pandoc pandoc-citeproc
```

### Kompilere selve dokumentasjonen

```bash
sudo Rscript -e 'devtools::install_github("rstudio/bookdown")' # kun hvis pakken ikke er installert enda
Rscript -e "rmarkdown::render_site(output_format = c('bookdown::gitbook', 'bookdown::pdf_book', 'bookdown::epub_book'), encoding = 'UTF-8')"
```

Siste linje kan erstattes med å kun kjøre scriptet `_build.sh`.
