# Instant Atlas

Dette kapitlet kan med fordel utvides.

## data.js

### Lage fila fra excel workbook

- `Tillegg` - `IA Export`
- Velg *JSON* og lagre som `data.js`

## config.xml

Kan enten modifiseres direkte eller gjennom InstantAtlas designer

## Design av selve atlaset

- Åpne *Instant atlas designer*
- Åpne config.xml
-

## Lage et atlas fra bunnen av

...


## Logo

- Hvis man ikke definerer både høyde og bredde, men kun en av de, på logo i `config.xml` vil skaleringen alltid være riktig. Definer bredde på logo nederst til venstre; høyde på logo øverst til venstre.
- Unngå å bruke jpg i logoer
- Logo med kun tekst kan lages med følgende svg-kode
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="900" height="66">
  <text x="10" y="50" font-family="Verdana" font-size="55"
        fill="#00509e" stroke="#00509e" stroke-width="2">
          Elderly (&#8805;75 years), 2013-2015
  </text>
</svg>
```

- `width` og `height` justeres slik at hele teksten kommer med (men ikke mer). Dette gjøres ved å åpne fil i nettleser samtidig som man endrer på verdiene.
- Det er mulig å bruke svg-filer på nettsidene, men har hatt noen problemer med dette i IA. Konverter figur til png, f.eks [her](http://svgtopng.com/)

## Legge ut et atlas på helseatlas.no

1. Gå inn på https://helseatlas.no/user og logg inn.
2. Trykk på *Legg til innhold* og velg *Atlas*.
3. Velg språk.
4. Gå til *Publiseringsvalg* og huk bort *Publisert*, siden vi ikke vil legge ut atlaset for publisering før alt er sjekket og klart.
5. Fyll ut punktene som har rød stjerne (*Navn* og *Tittel* i *Les mer*).
6. Last opp en zip-fil med IA-filene i *Filer til atlaset*-fanen.
7. Trykk på *Lagre*.

Senere kan man gå inn å legge til nye filer, erstatte filer, og publisere atlaset for alle. 
Så lenge man er logget inn kan man se atlaset på forsiden, slik det vil bli seende ut etter publisering.